# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool: RaspberryPi

variables:
  mvcServer: 'MVCWebApp'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Build
  displayName: "Build"
  jobs:
    - job: Buid
      displayName: "Build MVC server"
      steps:
        - task: DotNetCoreCLI@2
          inputs:
            command: 'restore'
            feedsToUse: 'select'
            projects: $(mvcServer)
        - task: DotNetCoreCLI@2
          inputs:
            command: 'build'
            projects: $(mvcServer)
            configuration: $(buildConfiguration)

        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: $(System.DefaultWorkingDirectory)/bin/$(mvcServer)
            artifactName: MVCServer
        
      




